// Seed list for the City combobox in the restaurant form — Phoenix metro
// first, then the rest of Arizona. Free text is still allowed; this is only
// the suggestion set. Add to it as places come up.

export const AZ_CITIES: readonly string[] = [
  // Phoenix metro
  'Phoenix',
  'Tempe',
  'Mesa',
  'Chandler',
  'Gilbert',
  'Scottsdale',
  'Glendale',
  'Peoria',
  'Surprise',
  'Goodyear',
  'Avondale',
  'Buckeye',
  'Queen Creek',
  'Fountain Hills',
  'Paradise Valley',
  'Cave Creek',
  'Carefree',
  'Apache Junction',
  'Tolleson',
  'El Mirage',
  'Litchfield Park',
  'Sun City',
  'Sun City West',
  'Anthem',
  // Greater Arizona
  'Tucson',
  'Flagstaff',
  'Sedona',
  'Prescott',
  'Prescott Valley',
  'Yuma',
  'Casa Grande',
  'Maricopa',
  'Lake Havasu City',
  'Kingman',
  'Bullhead City',
  'Sierra Vista',
  'Show Low',
  'Payson',
  'Cottonwood',
  'Williams',
  'Globe',
  'Page',
]
